const fs = require('fs');
const path = require('path');

function walkDir(dir) {
    let results = [];
    const list = fs.readdirSync(dir);
    list.forEach(file => {
        const fullPath = path.join(dir, file);
        const stat = fs.statSync(fullPath);
        if (stat && stat.isDirectory()) {
            results = results.concat(walkDir(fullPath));
        } else {
            results.push(fullPath);
        }
    });
    return results;
}

function formatName(filename) {
    let name = path.basename(filename, path.extname(filename));
    // Replace "_s" with "'s" (e.g. "outcast_s voyage" -> "outcast's voyage")
    name = name.replace(/_s\b/g, "'s");
    // Capitalize each word
    return name.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

const assetsDir = path.join(__dirname, 'assets');
if (!fs.existsSync(assetsDir)) {
    console.error("Assets directory not found at " + assetsDir);
    process.exit(1);
}

const files = walkDir(assetsDir);
const catalog = [];

files.forEach(file => {
    // Relative path using forward slashes
    const relativePath = path.relative(assetsDir, file).replace(/\\/g, '/');
    const parts = relativePath.split('/');
    
    // Ensure we have at least: [character]/[rarity]/[type]/...
    if (parts.length < 4) return;
    
    const character = parts[0];
    const rarityStr = parts[1];
    const type = parts[2];
    
    let rarity = 3;
    if (rarityStr === 'five-star') rarity = 5;
    else if (rarityStr === 'four-star') rarity = 4;
    else if (rarityStr === 'three-star') rarity = 3;
    else return;
    
    let bannerType = 'both';
    let cardFile = '';
    
    if (rarity === 5) {
        if (parts.length < 5) return;
        bannerType = parts[3]; // 'standard' or 'limited'
        cardFile = parts[4];
    } else {
        cardFile = parts[3];
    }
    
    if (!cardFile) return;
    
    const ext = path.extname(cardFile).toLowerCase();
    
    catalog.push({
        character: character,
        rarity: rarity,
        rarityStr: `${rarity}star`,
        type: type, // 'lunar' or 'solar'
        bannerType: bannerType, // 'standard', 'limited', 'both'
        assetPath: `assets/${relativePath}`,
        cardName: formatName(cardFile),
        isVideo: ext === '.mp4' || ext === '.mp4' || ext === '.webm'
    });
});

const output = `// Auto-generated by build_catalog.js
const CARD_CATALOG = ${JSON.stringify(catalog, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, 'cards.js'), output);
console.log(`Successfully generated cards.js with ${catalog.length} cards.`);
