// Auto-generated by build_catalog.js
const CARD_CATALOG = [
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/clearday return.mp4",
    "cardName": "Clearday Return",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/clearwind glide.mp4",
    "cardName": "Clearwind Glide",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/floating floraletter.mp4",
    "cardName": "Floating Floraletter",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/imperial thronesong.mp4",
    "cardName": "Imperial Thronesong",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/indulgent scheme.mp4",
    "cardName": "Indulgent Scheme",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/no-return night.mp4",
    "cardName": "No-return Night",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/painful signal.mp4",
    "cardName": "Painful Signal",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/passionate overload.mp4",
    "cardName": "Passionate Overload",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/tainted cuts.mp4",
    "cardName": "Tainted Cuts",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/up close.mp4",
    "cardName": "Up Close",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/vinesurge instinct.mp4",
    "cardName": "Vinesurge Instinct",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/wayward wonderland.mp4",
    "cardName": "Wayward Wonderland",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/lunar/limited/your skyblue.mp4",
    "cardName": "Your Skyblue",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/caleb/five-star/lunar/standard/endless summer.mp4",
    "cardName": "Endless Summer",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/caleb/five-star/lunar/standard/exclusive aftertaste.mp4",
    "cardName": "Exclusive Aftertaste",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/caleb/five-star/lunar/standard/hidden waves.mp4",
    "cardName": "Hidden Waves",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/caleb/five-star/lunar/standard/yearly nostalgia.mp4",
    "cardName": "Yearly Nostalgia",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/solar/limited/loneroad together.mp4",
    "cardName": "Loneroad Together",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/solar/limited/loneroad unreturned.mp4",
    "cardName": "Loneroad Unreturned",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/solar/limited/nether parting.mp4",
    "cardName": "Nether Parting",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/caleb/five-star/solar/limited/nether yearning.mp4",
    "cardName": "Nether Yearning",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "standard",
    "assetPath": "assets/caleb/five-star/solar/standard/farspace bloomfall.mp4",
    "cardName": "Farspace Bloomfall",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "standard",
    "assetPath": "assets/caleb/five-star/solar/standard/farspace deviation.mp4",
    "cardName": "Farspace Deviation",
    "isVideo": true
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/borrowed promise.png",
    "cardName": "Borrowed Promise",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/burnline.png",
    "cardName": "Burnline",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/chasing summer.png",
    "cardName": "Chasing Summer",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/deceptive solitude.png",
    "cardName": "Deceptive Solitude",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/held orchard.png",
    "cardName": "Held Orchard",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/intertwined gold.png",
    "cardName": "Intertwined Gold",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/lotus bond.png",
    "cardName": "Lotus Bond",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/skyline.png",
    "cardName": "Skyline",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/spotlit gaze.png",
    "cardName": "Spotlit Gaze",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/stage observer.png",
    "cardName": "Stage Observer",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/summer's echo.png",
    "cardName": "Summer's Echo",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/verdant wetlands.png",
    "cardName": "Verdant Wetlands",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/lunar/verified rumor.png",
    "cardName": "Verified Rumor",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/solar/duskshard dreams.png",
    "cardName": "Duskshard Dreams",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/solar/duskshard lotus.png",
    "cardName": "Duskshard Lotus",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/solar/farewell dreamscape.png",
    "cardName": "Farewell Dreamscape",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/solar/farewell intimacy.png",
    "cardName": "Farewell Intimacy",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/solar/longtime moments.png",
    "cardName": "Longtime Moments",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/caleb/four-star/solar/longtime yesterday.png",
    "cardName": "Longtime Yesterday",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/three-star/lunar/distant dreams.png",
    "cardName": "Distant Dreams",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/three-star/lunar/his gravity.png",
    "cardName": "His Gravity",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/three-star/lunar/literary immersion.png",
    "cardName": "Literary Immersion",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/three-star/lunar/maximum energy.png",
    "cardName": "Maximum Energy",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/three-star/lunar/skyward flair.png",
    "cardName": "Skyward Flair",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/three-star/lunar/stay in touch.png",
    "cardName": "Stay In Touch",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/caleb/three-star/lunar/the termination.png",
    "cardName": "The Termination",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/caleb/three-star/solar/critical strike.png",
    "cardName": "Critical Strike",
    "isVideo": false
  },
  {
    "character": "caleb",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/caleb/three-star/solar/perfect apple.png",
    "cardName": "Perfect Apple",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/boundless seas.mp4",
    "cardName": "Boundless Seas",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/carved gemheart.mp4",
    "cardName": "Carved Gemheart",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/destined dawntide.mp4",
    "cardName": "Destined Dawntide",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/duskbright steps.mp4",
    "cardName": "Duskbright Steps",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/extreme dose.mp4",
    "cardName": "Extreme Dose",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/fires of devotion.mp4",
    "cardName": "Fires Of Devotion",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/gem affection.mp4",
    "cardName": "Gem Affection",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/heatwave torrent.mp4",
    "cardName": "Heatwave Torrent",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/ignited echoes.mp4",
    "cardName": "Ignited Echoes",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/intertidal zone.mp4",
    "cardName": "Intertidal Zone",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/into the canvas.mp4",
    "cardName": "Into The Canvas",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/omnipotent perception.mp4",
    "cardName": "Omnipotent Perception",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/rippling blossoms.mp4",
    "cardName": "Rippling Blossoms",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/sunset on canvas.mp4",
    "cardName": "Sunset On Canvas",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/sweet overdrive.mp4",
    "cardName": "Sweet Overdrive",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/tailwag moment.mp4",
    "cardName": "Tailwag Moment",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/unforgettable adventure.mp4",
    "cardName": "Unforgettable Adventure",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/lunar/limited/wisteria waltz.mp4",
    "cardName": "Wisteria Waltz",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/rafayel/five-star/lunar/standard/before sunrise.mp4",
    "cardName": "Before Sunrise",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/rafayel/five-star/lunar/standard/blossoms.mp4",
    "cardName": "Blossoms",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/rafayel/five-star/lunar/standard/rising tides.mp4",
    "cardName": "Rising Tides",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/rafayel/five-star/lunar/standard/seething flames.mp4",
    "cardName": "Seething Flames",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/rafayel/five-star/lunar/standard/sparkling traces.mp4",
    "cardName": "Sparkling Traces",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/rafayel/five-star/lunar/standard/your fragrance.mp4",
    "cardName": "Your Fragrance",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/solar/limited/mistea descent.mp4",
    "cardName": "Mistea Descent",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/solar/limited/mistea lament.mp4",
    "cardName": "Mistea Lament",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/solar/limited/temple's promise.mp4",
    "cardName": "Temple's Promise",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/rafayel/five-star/solar/limited/temple's sunset.mp4",
    "cardName": "Temple's Sunset",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "standard",
    "assetPath": "assets/rafayel/five-star/solar/standard/deep sea riches.mp4",
    "cardName": "Deep Sea Riches",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "standard",
    "assetPath": "assets/rafayel/five-star/solar/standard/deep see promise.mp4",
    "cardName": "Deep See Promise",
    "isVideo": true
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/afternoon arclight.png",
    "cardName": "Afternoon Arclight",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/banquet ablaze.png",
    "cardName": "Banquet Ablaze",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/dangerously close.png",
    "cardName": "Dangerously Close",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/entwined.png",
    "cardName": "Entwined",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/eventide recitative.png",
    "cardName": "Eventide Recitative",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/flowery words.png",
    "cardName": "Flowery Words",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/fragrant dream.png",
    "cardName": "Fragrant Dream",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/glistening hearts.png",
    "cardName": "Glistening Hearts",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/hearty knock.png",
    "cardName": "Hearty Knock",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/hidden shadow.png",
    "cardName": "Hidden Shadow",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/ivory nightfall.png",
    "cardName": "Ivory Nightfall",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/journey seeker.png",
    "cardName": "Journey Seeker",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/lost in your eyes.png",
    "cardName": "Lost In Your Eyes",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/love's silhouette.png",
    "cardName": "Love's Silhouette",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/myths.png",
    "cardName": "Myths",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/ocean at night.png",
    "cardName": "Ocean At Night",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/oceanside exchange.png",
    "cardName": "Oceanside Exchange",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/promised wildfire.png",
    "cardName": "Promised Wildfire",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/scarlet invitation.png",
    "cardName": "Scarlet Invitation",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/scorching rain.png",
    "cardName": "Scorching Rain",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/sunlit raindrops.png",
    "cardName": "Sunlit Raindrops",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/tipsy.png",
    "cardName": "Tipsy",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/transparent ocean.png",
    "cardName": "Transparent Ocean",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/trueheart flip.png",
    "cardName": "Trueheart Flip",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/vesperine glimmer.png",
    "cardName": "Vesperine Glimmer",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/whalefall lament.png",
    "cardName": "Whalefall Lament",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/lunar/when light falls.png",
    "cardName": "When Light Falls",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/solar/daybreak's touch.png",
    "cardName": "Daybreak's Touch",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/solar/heartfelt game.png",
    "cardName": "Heartfelt Game",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/solar/heartfelt moment.png",
    "cardName": "Heartfelt Moment",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/solar/radiant halo.png",
    "cardName": "Radiant Halo",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/solar/radiant heart.png",
    "cardName": "Radiant Heart",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/solar/rainbow strokes.png",
    "cardName": "Rainbow Strokes",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/solar/sapphire dream.png",
    "cardName": "Sapphire Dream",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/solar/sapphire scar.png",
    "cardName": "Sapphire Scar",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/solar/tidefall allure.png",
    "cardName": "Tidefall Allure",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/four-star/solar/tidefall waves.png",
    "cardName": "Tidefall Waves",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/backlight.png",
    "cardName": "Backlight",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/bloom gaze.png",
    "cardName": "Bloom Gaze",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/cherished moment.png",
    "cardName": "Cherished Moment",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/dawn's melody.png",
    "cardName": "Dawn's Melody",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/distant prayer.png",
    "cardName": "Distant Prayer",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/do not disturb.png",
    "cardName": "Do Not Disturb",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/in your eyes.png",
    "cardName": "In Your Eyes",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/left on read.png",
    "cardName": "Left On Read",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/quick sketch.png",
    "cardName": "Quick Sketch",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/secret.png",
    "cardName": "Secret",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/social occasion.png",
    "cardName": "Social Occasion",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/swimming hearts.png",
    "cardName": "Swimming Hearts",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/take care of me.png",
    "cardName": "Take Care Of Me",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/thinking.png",
    "cardName": "Thinking",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/troubled.png",
    "cardName": "Troubled",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/trump card.png",
    "cardName": "Trump Card",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/whatcha doing.png",
    "cardName": "Whatcha Doing",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/lunar/wish granted.png",
    "cardName": "Wish Granted",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/solar/come with me.png",
    "cardName": "Come With Me",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/solar/inspiration search.png",
    "cardName": "Inspiration Search",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/solar/invitation.png",
    "cardName": "Invitation",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/solar/lame party.png",
    "cardName": "Lame Party",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/solar/not angry.png",
    "cardName": "Not Angry",
    "isVideo": false
  },
  {
    "character": "rafayel",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/rafayel/three-star/solar/perfect smile.png",
    "cardName": "Perfect Smile",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/alternative darkborne.mp4",
    "cardName": "Alternative Darkborne",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/darkbound souls.mp4",
    "cardName": "Darkbound Souls",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/finale undone.mp4",
    "cardName": "Finale Undone",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/goodcat code.mp4",
    "cardName": "Goodcat Code",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/grassland romance.mp4",
    "cardName": "Grassland Romance",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/improvised flow.mp4",
    "cardName": "Improvised Flow",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/innocent birdcage.mp4",
    "cardName": "Innocent Birdcage",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/kitten included.mp4",
    "cardName": "Kitten Included",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/lost oasis.mp4",
    "cardName": "Lost Oasis",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/lovespeed ride.mp4",
    "cardName": "Lovespeed Ride",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/night of secrecy.mp4",
    "cardName": "Night Of Secrecy",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/passionate appraisal.mp4",
    "cardName": "Passionate Appraisal",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/primordial chaos.mp4",
    "cardName": "Primordial Chaos",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/radiant brilliance.mp4",
    "cardName": "Radiant Brilliance",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/rainlit night.mp4",
    "cardName": "Rainlit Night",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/shared lanterns.mp4",
    "cardName": "Shared Lanterns",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/valleydream bloom.mp4",
    "cardName": "Valleydream Bloom",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/lunar/limited/where hearts live.mp4",
    "cardName": "Where Hearts Live",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/sylus/five-star/lunar/standard/immobilized.mp4",
    "cardName": "Immobilized",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/sylus/five-star/lunar/standard/magnum opus.mp4",
    "cardName": "Magnum Opus",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/sylus/five-star/lunar/standard/nightplumes.mp4",
    "cardName": "Nightplumes",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/sylus/five-star/lunar/standard/within reach.mp4",
    "cardName": "Within Reach",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/solar/limited/abyssal blossom.mp4",
    "cardName": "Abyssal Blossom",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/solar/limited/abyssal mark.mp4",
    "cardName": "Abyssal Mark",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/solar/limited/crimson departure.mp4",
    "cardName": "Crimson Departure",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/sylus/five-star/solar/limited/crimson rapture.mp4",
    "cardName": "Crimson Rapture",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "standard",
    "assetPath": "assets/sylus/five-star/solar/standard/captivating flavor.mp4",
    "cardName": "Captivating Flavor",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "standard",
    "assetPath": "assets/sylus/five-star/solar/standard/captivating lesson.mp4",
    "cardName": "Captivating Lesson",
    "isVideo": true
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/approaching dusk.png",
    "cardName": "Approaching Dusk",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/awaiting.png",
    "cardName": "Awaiting",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/chaotic velocity.png",
    "cardName": "Chaotic Velocity",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/continuous symphony.png",
    "cardName": "Continuous Symphony",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/freefall gambit.png",
    "cardName": "Freefall Gambit",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/grasped dominion.png",
    "cardName": "Grasped Dominion",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/greedy heart.png",
    "cardName": "Greedy Heart",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/melodic weave.png",
    "cardName": "Melodic Weave",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/nightglow.png",
    "cardName": "Nightglow",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/no way out.png",
    "cardName": "No Way Out",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/ordinary traces.png",
    "cardName": "Ordinary Traces",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/rosy hues.png",
    "cardName": "Rosy Hues",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/searing touch.png",
    "cardName": "Searing Touch",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/shared bliss.png",
    "cardName": "Shared Bliss",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/tender curve.png",
    "cardName": "Tender Curve",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/lunar/wild gaze.png",
    "cardName": "Wild Gaze",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/solar/bloodnight blaze.png",
    "cardName": "Bloodnight Blaze",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/solar/bloodnight drift.png",
    "cardName": "Bloodnight Drift",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/solar/ivory prudence.png",
    "cardName": "Ivory Prudence",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/solar/ivory thirst.png",
    "cardName": "Ivory Thirst",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/solar/razor's dance.png",
    "cardName": "Razor's Dance",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/sylus/four-star/solar/razor's grip.png",
    "cardName": "Razor's Grip",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/three-star/lunar/composed.png",
    "cardName": "Composed",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/three-star/lunar/dry ace.png",
    "cardName": "Dry Ace",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/three-star/lunar/gifted arrival.png",
    "cardName": "Gifted Arrival",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/three-star/lunar/gutsy rush.png",
    "cardName": "Gutsy Rush",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/three-star/lunar/my decision.png",
    "cardName": "My Decision",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/three-star/lunar/reckless living.png",
    "cardName": "Reckless Living",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/three-star/lunar/satiated.png",
    "cardName": "Satiated",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/three-star/lunar/shoo-in.png",
    "cardName": "Shoo-in",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/sylus/three-star/lunar/taking control.png",
    "cardName": "Taking Control",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/sylus/three-star/solar/in charge.png",
    "cardName": "In Charge",
    "isVideo": false
  },
  {
    "character": "sylus",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/sylus/three-star/solar/just encounter.png",
    "cardName": "Just Encounter",
    "isVideo": false
  },
  {
    "character": "valko",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/valko/four-star/lunar/charging password.png",
    "cardName": "Charging Password",
    "isVideo": false
  },
  {
    "character": "valko",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/valko/four-star/lunar/foregone fall.png",
    "cardName": "Foregone Fall",
    "isVideo": false
  },
  {
    "character": "valko",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/valko/four-star/lunar/the tameless game.png",
    "cardName": "The Tameless Game",
    "isVideo": false
  },
  {
    "character": "valko",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/valko/four-star/lunar/under staidrain.png",
    "cardName": "Under Staidrain",
    "isVideo": false
  },
  {
    "character": "valko",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/valko/four-star/solar/IMG_6837.PNG",
    "cardName": "IMG_6837",
    "isVideo": false
  },
  {
    "character": "valko",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/valko/four-star/solar/IMG_6838.PNG",
    "cardName": "IMG_6838",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/between stars.mp4",
    "cardName": "Between Stars",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/blades with blossoms.mp4",
    "cardName": "Blades With Blossoms",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/celestial message.mp4",
    "cardName": "Celestial Message",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/coolsplash soak.mp4",
    "cardName": "Coolsplash Soak",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/deluded fiction.mp4",
    "cardName": "Deluded Fiction",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/eulogy of light.mp4",
    "cardName": "Eulogy Of Light",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/faint sensation.mp4",
    "cardName": "Faint Sensation",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/feverish attempts.mp4",
    "cardName": "Feverish Attempts",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/floof attack.mp4",
    "cardName": "Floof Attack",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/floral blessing.mp4",
    "cardName": "Floral Blessing",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/inflorescence imprints.mp4",
    "cardName": "Inflorescence Imprints",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/misty silhouette.mp4",
    "cardName": "Misty Silhouette",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/no restraint.mp4",
    "cardName": "No Restraint",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/offbeat track.mp4",
    "cardName": "Offbeat Track",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/runaway hearts.mp4",
    "cardName": "Runaway Hearts",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/silvery polyphony.mp4",
    "cardName": "Silvery Polyphony",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/starfall sanctuary.mp4",
    "cardName": "Starfall Sanctuary",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/sunken glow.mp4",
    "cardName": "Sunken Glow",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/tender night.mp4",
    "cardName": "Tender Night",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/lunar/limited/tranquil moments.mp4",
    "cardName": "Tranquil Moments",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/xavier/five-star/lunar/standard/fluffy trap.mp4",
    "cardName": "Fluffy Trap",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/xavier/five-star/lunar/standard/fragment of time.mp4",
    "cardName": "Fragment Of Time",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/xavier/five-star/lunar/standard/outcast's voyage.mp4",
    "cardName": "Outcast's Voyage",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/xavier/five-star/lunar/standard/precious bonfire.mp4",
    "cardName": "Precious Bonfire",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/xavier/five-star/lunar/standard/precious moment.mp4",
    "cardName": "Precious Moment",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/xavier/five-star/lunar/standard/unique aftertaste.mp4",
    "cardName": "Unique Aftertaste",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/solar/limited/midnight rainfall.mp4",
    "cardName": "Midnight Rainfall",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/solar/limited/midnight whispers.mp4",
    "cardName": "Midnight Whispers",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/solar/limited/nightvow mooncurse.mp4",
    "cardName": "Nightvow Mooncurse",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/xavier/five-star/solar/limited/nightvow requiem.mp4",
    "cardName": "Nightvow Requiem",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "standard",
    "assetPath": "assets/xavier/five-star/solar/standard/lightseeking obsession.mp4",
    "cardName": "Lightseeking Obsession",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "standard",
    "assetPath": "assets/xavier/five-star/solar/standard/lightseeking shadowrend.mp4",
    "cardName": "Lightseeking Shadowrend",
    "isVideo": true
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/a captured moment.png",
    "cardName": "A Captured Moment",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/a day of snow.png",
    "cardName": "A Day Of Snow",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/celestial yearn.png",
    "cardName": "Celestial Yearn",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/close feelings.png",
    "cardName": "Close Feelings",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/dawn to dusk.png",
    "cardName": "Dawn To Dusk",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/dreaming.png",
    "cardName": "Dreaming",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/dreams within reach.png",
    "cardName": "Dreams Within Reach",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/enlightenment.png",
    "cardName": "Enlightenment",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/firelit embrace.png",
    "cardName": "Firelit Embrace",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/galactic harmony.png",
    "cardName": "Galactic Harmony",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/garden of secrets.png",
    "cardName": "Garden Of Secrets",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/horizon's pulse.png",
    "cardName": "Horizon's Pulse",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/lost signal.png",
    "cardName": "Lost Signal",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/love syndrome.png",
    "cardName": "Love Syndrome",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/moments refined.png",
    "cardName": "Moments Refined",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/nocturnal hunt.png",
    "cardName": "Nocturnal Hunt",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/perfect sunset.png",
    "cardName": "Perfect Sunset",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/planned crush.png",
    "cardName": "Planned Crush",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/seeker of light.png",
    "cardName": "Seeker Of Light",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/shimmering sunlight.png",
    "cardName": "Shimmering Sunlight",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/spring letter.png",
    "cardName": "Spring Letter",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/starry sound.png",
    "cardName": "Starry Sound",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/sweetness pursuit.png",
    "cardName": "Sweetness Pursuit",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/twofold heartbeat.png",
    "cardName": "Twofold Heartbeat",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/unreturned traveler.png",
    "cardName": "Unreturned Traveler",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/warm wishes.png",
    "cardName": "Warm Wishes",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/lunar/winter's sun.png",
    "cardName": "Winter's Sun",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/solar/an appointment.png",
    "cardName": "An Appointment",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/solar/gilded dreams.png",
    "cardName": "Gilded Dreams",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/solar/gilded mirage.png",
    "cardName": "Gilded Mirage",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/solar/heartfelt code.png",
    "cardName": "Heartfelt Code",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/solar/heartfelt guide.png",
    "cardName": "Heartfelt Guide",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/solar/moment's respite.png",
    "cardName": "Moment's Respite",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/solar/shining light.png",
    "cardName": "Shining Light",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/solar/shining traces.png",
    "cardName": "Shining Traces",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/solar/veiled guardian.png",
    "cardName": "Veiled Guardian",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/four-star/solar/veiled starlight.png",
    "cardName": "Veiled Starlight",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/about to hit the ball.png",
    "cardName": "About To Hit The Ball",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/ardent threads.png",
    "cardName": "Ardent Threads",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/bad idea.png",
    "cardName": "Bad Idea",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/calls.png",
    "cardName": "Calls",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/combat ready.png",
    "cardName": "Combat Ready",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/energy drink.png",
    "cardName": "Energy Drink",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/guardian.png",
    "cardName": "Guardian",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/holding hands.png",
    "cardName": "Holding Hands",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/listen.png",
    "cardName": "Listen",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/nestle.png",
    "cardName": "Nestle",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/real look.png",
    "cardName": "Real Look",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/recall.png",
    "cardName": "Recall",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/reflection.png",
    "cardName": "Reflection",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/silent swipe.png",
    "cardName": "Silent Swipe",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/starry stroll.png",
    "cardName": "Starry Stroll",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/the rain.png",
    "cardName": "The Rain",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/lunar/unfading wish.png",
    "cardName": "Unfading Wish",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/solar/a break.png",
    "cardName": "A Break",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/solar/apple of my eye.png",
    "cardName": "Apple Of My Eye",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/solar/blade.png",
    "cardName": "Blade",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/solar/gaze.png",
    "cardName": "Gaze",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/solar/good morning.png",
    "cardName": "Good Morning",
    "isVideo": false
  },
  {
    "character": "xavier",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/xavier/three-star/solar/heart-to-heart.png",
    "cardName": "Heart-to-heart",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/absolute zeal.mp4",
    "cardName": "Absolute Zeal",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/aeon's canon.mp4",
    "cardName": "Aeon's Canon",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/dawn and devotion.mp4",
    "cardName": "Dawn And Devotion",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/dawnbreak promise.mp4",
    "cardName": "Dawnbreak Promise",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/drunken intimacy.mp4",
    "cardName": "Drunken Intimacy",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/entwined kites.mp4",
    "cardName": "Entwined Kites",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/eternal attachment.mp4",
    "cardName": "Eternal Attachment",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/everlasting wish.mp4",
    "cardName": "Everlasting Wish",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/exclusive tutorial.mp4",
    "cardName": "Exclusive Tutorial",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/fluffy treatment.mp4",
    "cardName": "Fluffy Treatment",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/fragrant possession.mp4",
    "cardName": "Fragrant Possession",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/heartstring notes.mp4",
    "cardName": "Heartstring Notes",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/hidden motive.mp4",
    "cardName": "Hidden Motive",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/iceborn warmth.mp4",
    "cardName": "Iceborn Warmth",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/immediate disorder.mp4",
    "cardName": "Immediate Disorder",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/medical rescue.mp4",
    "cardName": "Medical Rescue",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/moonlit dream.mp4",
    "cardName": "Moonlit Dream",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/runaway waves.mp4",
    "cardName": "Runaway Waves",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/secret's kiss.mp4",
    "cardName": "Secret's Kiss",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/lunar/limited/silent underflow.mp4",
    "cardName": "Silent Underflow",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/zayne/five-star/lunar/standard/business trip.mp4",
    "cardName": "Business Trip",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/zayne/five-star/lunar/standard/cozy afternoon.mp4",
    "cardName": "Cozy Afternoon",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/zayne/five-star/lunar/standard/engraved affection.mp4",
    "cardName": "Engraved Affection",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/zayne/five-star/lunar/standard/frozen nightfall.mp4",
    "cardName": "Frozen Nightfall",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "lunar",
    "bannerType": "standard",
    "assetPath": "assets/zayne/five-star/lunar/standard/gentle twilight.mp4",
    "cardName": "Gentle Twilight",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/solar/limited/diviner's hymn.mp4",
    "cardName": "Diviner's Hymn",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/solar/limited/diviner's stillness.mp4",
    "cardName": "Diviner's Stillness",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/solar/limited/snowfall embrace.mp4",
    "cardName": "Snowfall Embrace",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "limited",
    "assetPath": "assets/zayne/five-star/solar/limited/snowfall encounter.mp4",
    "cardName": "Snowfall Encounter",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "standard",
    "assetPath": "assets/zayne/five-star/solar/standard/forever sealed.mp4",
    "cardName": "Forever Sealed",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 5,
    "rarityStr": "5star",
    "type": "solar",
    "bannerType": "standard",
    "assetPath": "assets/zayne/five-star/solar/standard/promise everlasting.mp4",
    "cardName": "Promise Everlasting",
    "isVideo": true
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/5th intercostal space.png",
    "cardName": "5th Intercostal Space",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/a long night.png",
    "cardName": "A Long Night",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/beginning.png",
    "cardName": "Beginning",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/blooming hour.png",
    "cardName": "Blooming Hour",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/chasing silhouettes.png",
    "cardName": "Chasing Silhouettes",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/cherished longing.png",
    "cardName": "Cherished Longing",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/dawn_s shadows.png",
    "cardName": "Dawn's Shadows",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/delicacy.png",
    "cardName": "Delicacy",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/destiny.png",
    "cardName": "Destiny",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/doomsday.png",
    "cardName": "Doomsday",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/dream revisited.png",
    "cardName": "Dream Revisited",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/everlasting snowdrop.png",
    "cardName": "Everlasting Snowdrop",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/fleeting sweetness.png",
    "cardName": "Fleeting Sweetness",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/fragmented dreams.png",
    "cardName": "Fragmented Dreams",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/frost salvation.png",
    "cardName": "Frost Salvation",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/glittering lights.png",
    "cardName": "Glittering Lights",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/holding autumn.png",
    "cardName": "Holding Autumn",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/morning drift.png",
    "cardName": "Morning Drift",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/ramblings come true.png",
    "cardName": "Ramblings Come True",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/secret fairytale.png",
    "cardName": "Secret Fairytale",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/silent poem.png",
    "cardName": "Silent Poem",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/spring remnants.png",
    "cardName": "Spring Remnants",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/stacked pulses.png",
    "cardName": "Stacked Pulses",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/steamy proximity.png",
    "cardName": "Steamy Proximity",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/surprise encounter.png",
    "cardName": "Surprise Encounter",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/sweet conspiracy.png",
    "cardName": "Sweet Conspiracy",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/lunar/thoughtful words.png",
    "cardName": "Thoughtful Words",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/solar/finale_s ache.png",
    "cardName": "Finale's Ache",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/solar/finale_s perpetuity.png",
    "cardName": "Finale's Perpetuity",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/solar/forest_s breeze.png",
    "cardName": "Forest's Breeze",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/solar/forest_s slumber.png",
    "cardName": "Forest's Slumber",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/solar/heartfelt encounter.png",
    "cardName": "Heartfelt Encounter",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/solar/heartfelt paradise.png",
    "cardName": "Heartfelt Paradise",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/solar/neon night.png",
    "cardName": "Neon Night",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/solar/starry nocturne.png",
    "cardName": "Starry Nocturne",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/solar/tranquil heart.png",
    "cardName": "Tranquil Heart",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 4,
    "rarityStr": "4star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/four-star/solar/tranquil moment.png",
    "cardName": "Tranquil Moment",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/aromatic.png",
    "cardName": "Aromatic",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/clean-up.png",
    "cardName": "Clean-up",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/crystal world.png",
    "cardName": "Crystal World",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/demeanor.png",
    "cardName": "Demeanor",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/doctor_s orders.png",
    "cardName": "Doctor's Orders",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/fated reunion.png",
    "cardName": "Fated Reunion",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/gaze from afar.png",
    "cardName": "Gaze From Afar",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/glasses.png",
    "cardName": "Glasses",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/injection therapy.png",
    "cardName": "Injection Therapy",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/lost in thought.png",
    "cardName": "Lost In Thought",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/precious treasure.png",
    "cardName": "Precious Treasure",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/secrets of fate.png",
    "cardName": "Secrets Of Fate",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/shining blessing.png",
    "cardName": "Shining Blessing",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/sweet burden.png",
    "cardName": "Sweet Burden",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/treasure in palm.png",
    "cardName": "Treasure In Palm",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/waiting.png",
    "cardName": "Waiting",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "lunar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/lunar/work plan.png",
    "cardName": "Work Plan",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/solar/auscultation.png",
    "cardName": "Auscultation",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/solar/checkup.png",
    "cardName": "Checkup",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/solar/little world.png",
    "cardName": "Little World",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/solar/no.png",
    "cardName": "No",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/solar/playing around.png",
    "cardName": "Playing Around",
    "isVideo": false
  },
  {
    "character": "zayne",
    "rarity": 3,
    "rarityStr": "3star",
    "type": "solar",
    "bannerType": "both",
    "assetPath": "assets/zayne/three-star/solar/thoughts.png",
    "cardName": "Thoughts",
    "isVideo": false
  }
];
